// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDckK8u84Di0LCLVp4BSBhdixMu_Xtm8kw',
    appId: '1:724386208664:web:159543e84aa11461a529ed',
    messagingSenderId: '724386208664',
    projectId: 'kajulink-ef612',
    authDomain: 'kajulink-ef612.firebaseapp.com',
    storageBucket: 'kajulink-ef612.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCO_3emfG5pOUCqzBE8VYic-V09DcnDZOE',
    appId: '1:724386208664:android:9cac4b5609e11f78a529ed',
    messagingSenderId: '724386208664',
    projectId: 'kajulink-ef612',
    storageBucket: 'kajulink-ef612.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCnc0R9lFMpq77tFkYSZPws3K8Kx4XymyU',
    appId: '1:724386208664:ios:aa28adb4ee30a844a529ed',
    messagingSenderId: '724386208664',
    projectId: 'kajulink-ef612',
    storageBucket: 'kajulink-ef612.firebasestorage.app',
    iosClientId: '724386208664-m0etuqg0793rfo08uetfvr8c66n2s2jr.apps.googleusercontent.com',
    iosBundleId: 'com.example.untitled2',
  );
}
